import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: "Dharavahik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Analytics />
        {children}
        <Footer />
      </body>
    </html>
  );
}
